### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by kirill3333** [P0lip/react-intl-optimizer#1]
Hi @P0lip 
First of all, thank you for your project.
How do you think is it possible to use with React native and https://github.com/yahoo/react-intl 
If yes can you add some instructions on how to setup it?

**Comment by P0lip** [comment]
Hello @kirill3333 
Thanks a lot for reaching out.

> How do you think is it possible to use with React native and https://github.com/yahoo/react-intl

Yes, the package is specifically meant to work with Yahoo's react-intl and it should work fine with React Native as long as all scripts containing react-intl messages are transformed by Webpack.

Would having some example project in this repo help with setting it up?
Happy to leave the instruction there.

**Comment by kirill3333** [comment]
@P0lip yes sure, if it possible, I think it would be helpful.

**Comment by P0lip** [comment]
Great! I'll create some reasonable example project today.

**Comment by P0lip** [comment]
@kirill3333 see https://github.com/P0lip/react-intl-optimizer/tree/master/examples/project
Let me know if it's any more clear for you now. :)
